USE MOPS;

-- Tabela Disc
ALTER TABLE Disc ADD PRIMARY KEY(idDisc);

ALTER TABLE Disc
    MODIFY idDisc INT AUTO_INCREMENT;

ALTER TABLE Disc AUTO_INCREMENT=0;

-- Tabela Artist
ALTER TABLE Artist ADD PRIMARY KEY(idArtist);

ALTER TABLE Artist
    MODIFY idArtist INT AUTO_INCREMENT;

ALTER TABLE Artist AUTO_INCREMENT=0;

-- Tabela User
ALTER TABLE User ADD PRIMARY KEY(firebaseID);

ALTER TABLE User
    MODIFY firebaseID INT AUTO_INCREMENT;

ALTER TABLE User AUTO_INCREMENT=0;

-- Tabela Song
ALTER TABLE Song ADD PRIMARY KEY(idSong);

ALTER TABLE Song
    MODIFY idSong INT AUTO_INCREMENT;

ALTER TABLE Song AUTO_INCREMENT=0;

-- Tabela CartItem
ALTER TABLE CartItem ADD PRIMARY KEY(idCartItem);

ALTER TABLE CartItem
    MODIFY idCartItem INT AUTO_INCREMENT;

ALTER TABLE CartItem AUTO_INCREMENT=0;

ALTER TABLE CartItem ADD CONSTRAINT fk_User_Cart FOREIGN KEY (firebaseID)
    REFERENCES User(firebaseID) ON DELETE CASCADE ON UPDATE CASCADE;

-- Tabela Genre
ALTER TABLE Genre ADD PRIMARY KEY(idGenre);

ALTER TABLE Genre
    MODIFY idGenre INT AUTO_INCREMENT;

ALTER TABLE Genre AUTO_INCREMENT=0;

ALTER TABLE Genre ADD CONSTRAINT fk_Genre_Song FOREIGN KEY (idSong)
    REFERENCES Song(idSong) ON DELETE CASCADE ON UPDATE CASCADE;


-- Tabela SpotifyLikedSong
ALTER TABLE SpotifyLikedSong ADD PRIMARY KEY(idSpotifyLikedSong);

ALTER TABLE SpotifyLikedSong
    MODIFY idSpotifyLikedSong INT AUTO_INCREMENT;

ALTER TABLE SpotifyLikedSong AUTO_INCREMENT=0;

ALTER TABLE SpotifyLikedSong ADD CONSTRAINT fk_SpotifyLikedSong_User FOREIGN KEY (firebaseID)
    REFERENCES User(firebaseID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE SpotifyLikedSong ADD CONSTRAINT fk_SpotifyLikedSong_Song FOREIGN KEY (idSong)
    REFERENCES Song(idSong) ON DELETE CASCADE ON UPDATE CASCADE;

-- Tabela SongArtistFeature

ALTER TABLE SongArtistFeature ADD PRIMARY KEY(idSongArtistFeature);

ALTER TABLE SongArtistFeature
    MODIFY idSongArtistFeature INT AUTO_INCREMENT;

ALTER TABLE SongArtistFeature AUTO_INCREMENT=0;

ALTER TABLE SongArtistFeature ADD CONSTRAINT fk_SongArtistFeature_Artist FOREIGN KEY (idArtist)
    REFERENCES Artist(idArtist) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE SongArtistFeature ADD CONSTRAINT fk_SongArtistFeature_Song FOREIGN KEY (idSong)
    REFERENCES Song(idSong) ON DELETE CASCADE ON UPDATE CASCADE;