SET GLOBAL local_infile = 1;


USE MOPS;

LOAD DATA LOCAL INFILE '/home/vlad/MOPS-backend/db/MOPS_CSVs/Disc.csv'
INTO TABLE Disc
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/vlad/MOPS-backend/db/MOPS_CSVs/Artist.csv'
INTO TABLE Artist
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/vlad/MOPS-backend/db/MOPS_CSVs/Genre.csv'
INTO TABLE Genre
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/vlad/MOPS-backend/db/MOPS_CSVs/Song.csv'
INTO TABLE Song
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/vlad/MOPS-backend/db/MOPS_CSVs/User.csv'
INTO TABLE User
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/vlad/MOPS-backend/db/MOPS_CSVs/CartItem.csv'
INTO TABLE CartItem
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/vlad/MOPS-backend/db/MOPS_CSVs/SpotifyLikedSong.csv'
INTO TABLE SpotifyLikedSong
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/vlad/MOPS-backend/db/MOPS_CSVs/SongGenre.csv'
INTO TABLE SongGenre
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/vlad/MOPS-backend/db/MOPS_CSVs/DiscSong.csv'
INTO TABLE DiscSong
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(idDisc,idSong);

LOAD DATA LOCAL INFILE '/home/vlad/MOPS-backend/db/MOPS_CSVs/SongArtistFeature.csv'
INTO TABLE SongArtistFeature
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(idSong,idArtist,importance);